In [7]:
# import re
# import time
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.chrome.service import Service
# from selenium.webdriver.chrome.options import Options
# from webdriver_manager.chrome import ChromeDriverManager
# import pandas as pd
# import numpy as np
# from datetime import datetime
# import os

# current_time = datetime.now().strftime('%Y-%m-%d_%H-%M')

# opts = Options()
# folder_name = f"Superbids/Superbids{current_time}"
# folder_path = os.path.join(r"D:/Automation/OutputW", folder_name)
# if not os.path.exists(folder_path):
#     os.makedirs(folder_path)

# prefs = {
#     "download.default_directory": folder_path
# }
# opts.add_experimental_option('prefs', prefs)

# # Use ChromeDriverManager to get the appropriate version of ChromeDriver
# service = Service(ChromeDriverManager().install())
# browser = webdriver.Chrome(service=service, options=opts)
# browser.maximize_window()
# browser.get("https://sheerdrivepro.com/home/")
# time.sleep(2)

# browser.find_element(By.ID, "mat-input-0").send_keys("SB108000R")
# browser.find_element(By.ID, "mat-input-1").send_keys("Moni@143")
# time.sleep(5)
# browser.find_element(By.XPATH, "/html/body/app-root/app-home/div/app-header/mat-sidenav-container/mat-sidenav-content/div/section[2]/div/mat-card/div/mat-card-content/div/form/button[1]").click()
# time.sleep(3)

# elements = browser.find_elements(By.XPATH, "/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card")
# print(len(elements))

# count = 0
# headings = ['Client', 'Start Date', 'End Date', 'Count', 'Category', 'Zone']
# temp_data = pd.DataFrame(columns=headings)

# for i in range(len(elements)):
#     title = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-header/div[2]/a/strong")
#     start_time = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[1]/p[1]/span")
#     end_time = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[1]/p[1]/span")
#     count_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[2]/p[1]")
#     category_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[2]/p")
#     zone_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-header/div[2]/p")

#     count += 1
#     temp_data.loc[len(temp_data)] = [title.text, start_time.text, end_time.text, count_vehicle.text, category_vehicle.text, zone_vehicle.text]

# temp_data.replace({col: {'' : np.nan} for col in headings}, inplace=True)
# temp_data.dropna(inplace=True)
# temp_data['Start Date'] = temp_data['Start Date'].apply(lambda x: pd.to_datetime(x).strftime('%d-%b-%Y'))
# temp_data['End Date'] = temp_data['End Date'].apply(lambda x: pd.to_datetime(x).strftime('%d-%b-%Y'))
# temp_data['Count'] = temp_data['Count'].apply(lambda x: int(re.search(r'\d+', str(x)).group()))

# try:
#     temp_data['Zone'] = temp_data['Zone'].apply(lambda x: x.split('\n')[1])
# except:
#     temp_data['Zone'] = temp_data['Zone']

# temp_data['Category'] = temp_data['Category'].str.replace(',', ' ')

# temp_data['Cat_first'] = temp_data['Category'].apply(lambda x: x.split(',')[0].strip())
# temp_data['Cat_last'] = temp_data['Category'].apply(lambda x: x.split(',')[-1].strip())

# split_client_first = []
# split_client_last = []

# for idx, row in temp_data.iterrows():
#     split_first = row['Client'].split(row['Cat_first'])[0].strip() if row['Cat_first'] in row['Client'] else row['Client']
#     split_last = row['Client'].split(row['Cat_last'])[-1].strip() if row['Cat_last'] in row['Client'] else row['Client']
#     split_client_first.append(split_first)
#     split_client_last.append(split_last)

# temp_data['Split_Client_first'] = split_client_first
# temp_data['Split_Client_last'] = split_client_last

# # Initialize the Location column to avoid KeyError
# temp_data['Location'] = ''

# for index, row in temp_data.iterrows():
#     if 'Insurance Salvage' in row['Split_Client_first']:
#         temp_data.at[index, 'Client'] = 'Insurance Salvage'
#         temp_data.at[index, 'Location'] = row['Zone']
#     else:
#         temp_data.at[index, 'Client'] = row['Split_Client_first'].split('-')[1].strip() if '-' in row['Split_Client_first'] else row['Split_Client_first']
#         temp_data.at[index, 'Location'] = row['Split_Client_last'].split('Online')[0].strip() if 'Online' in row['Split_Client_last'] else row['Split_Client_last']

# final_temp = temp_data[['Client', 'Start Date', 'End Date', 'Count', 'Category', 'Location', 'Zone']]
# current_time = datetime.now().strftime('%Y-%m-%d %H-%M-%S')
# file = f"SuperBids{current_time}"

# try:
#     final_temp.to_excel(f"D:/Automation/OutputW/{folder_name}/{file}.xlsx")
#     print('Done')
# except Exception as e:
#     print(f'Error: {e}')

# browser.quit()

0
Done

In [10]:
final_temp

,Client,Start Date,End Date,Count,Category,Location,Zone
0,ICICI Bank,06-Aug-2024,06-Aug-2024,14,CV,West,West
1,Yes Bank,03-Aug-2024,03-Aug-2024,2,4W,Assam,East
2,Yes Bank,03-Aug-2024,03-Aug-2024,1,4W,Jharkhand,East
3,Yes Bank,03-Aug-2024,03-Aug-2024,1,CE,Orissa,East
4,Yes Bank,03-Aug-2024,03-Aug-2024,4,4W,West Bengal,East
...,...,...,...,...,...,...,...
186,Bajaj Finance,06-Aug-2024,06-Aug-2024,2,3W,West Bengal,East
187,Bajaj Finance,06-Aug-2024,06-Aug-2024,192,2W,Orissa,East
188,Bajaj Finance,06-Aug-2024,06-Aug-2024,42,3W,Orissa,East
189,Consumer,01-Aug-2024,01-Aug-2024,10,4W,Gujarat,West
190,Consumer,01-Aug-2024,01-Aug-2024,10,4W,Maharashtra,West

In [1]:
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import numpy as np
from datetime import datetime
import os

# Get the current time for folder and file naming
current_time = datetime.now().strftime('%Y-%m-%d_%H-%M')

opts = Options()
folder_name = f"Superbids/Superbids{current_time}"
folder_path = os.path.join(r"D:/Automation/OutputW", folder_name)
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

prefs = {
    "download.default_directory": folder_path
}
opts.add_experimental_option('prefs', prefs)

# Use ChromeDriverManager to get the appropriate version of ChromeDriver
service = Service(ChromeDriverManager().install())
browser = webdriver.Chrome(service=service, options=opts)
browser.maximize_window()
browser.get("https://sheerdrivepro.com/home/")
time.sleep(2)

browser.find_element(By.ID, "mat-input-0").send_keys("SB106126P")
browser.find_element(By.ID, "mat-input-1").send_keys("Test@234")
time.sleep(5)
browser.find_element(By.XPATH, "/html/body/app-root/app-home/div/app-header/mat-sidenav-container/mat-sidenav-content/div/section[2]/div/mat-card/div/mat-card-content/div/form/button[1]").click()
time.sleep(3)

elements = browser.find_elements(By.XPATH, "/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card")
print(len(elements))

count = 0
headings = ['Client', 'Start Date', 'End Date', 'Count', 'Category', 'Zone']
temp_data = pd.DataFrame(columns=headings)

for i in range(len(elements)):
    title = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-header/div[2]/a/strong")
    start_time = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[1]/p[1]/span")
    end_time = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[1]/p[1]/span")
    count_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[2]/p[1]")
    category_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-content/div[1]/div[2]/p")
    zone_vehicle = browser.find_element(By.XPATH, f"/html/body/app-root/app-events/app-side-nav/mat-sidenav-container/mat-sidenav-content/div/mat-drawer-container/mat-drawer-content/div/div[2]/div/mat-card[{i+1}]/mat-card-header/div[2]/p")

    count += 1
    temp_data.loc[len(temp_data)] = [title.text, start_time.text, end_time.text, count_vehicle.text, category_vehicle.text, zone_vehicle.text]

temp_data.replace({col: {'' : np.nan} for col in headings}, inplace=True)
temp_data.dropna(inplace=True)
temp_data['Start Date'] = temp_data['Start Date'].apply(lambda x: pd.to_datetime(x).strftime('%d-%b-%Y'))
temp_data['End Date'] = temp_data['End Date'].apply(lambda x: pd.to_datetime(x).strftime('%d-%b-%Y'))
temp_data['Count'] = temp_data['Count'].apply(lambda x: int(re.search(r'\d+', str(x)).group()))

try:
    temp_data['Zone'] = temp_data['Zone'].apply(lambda x: x.split('\n')[1])
except:
    temp_data['Zone'] = temp_data['Zone']

temp_data['Category'] = temp_data['Category'].str.replace(',', ' ')

temp_data['Cat_first'] = temp_data['Category'].apply(lambda x: x.split(',')[0].strip())
temp_data['Cat_last'] = temp_data['Category'].apply(lambda x: x.split(',')[-1].strip())

split_client_first = []
split_client_last = []

for idx, row in temp_data.iterrows():
    split_first = row['Client'].split(row['Cat_first'])[0].strip() if row['Cat_first'] in row['Client'] else row['Client']
    split_last = row['Client'].split(row['Cat_last'])[-1].strip() if row['Cat_last'] in row['Client'] else row['Client']
    split_client_first.append(split_first)
    split_client_last.append(split_last)

temp_data['Split_Client_first'] = split_client_first
temp_data['Split_Client_last'] = split_client_last

# Initialize the Location column to avoid KeyError
temp_data['Location'] = ''

for index, row in temp_data.iterrows():
    if 'Insurance Salvage' in row['Split_Client_first']:
        temp_data.at[index, 'Client'] = 'Insurance Salvage'
        temp_data.at[index, 'Location'] = row['Zone']
    else:
        temp_data.at[index, 'Client'] = row['Split_Client_first'].split('-')[1].strip() if '-' in row['Split_Client_first'] else row['Split_Client_first']
        temp_data.at[index, 'Location'] = row['Split_Client_last'].split('Online')[0].strip() if 'Online' in row['Split_Client_last'] else row['Split_Client_last']

final_temp = temp_data[['Client', 'Start Date', 'End Date', 'Count', 'Category', 'Location', 'Zone']]
current_time = datetime.now().strftime('%Y-%m-%d %H-%M-%S')
file = f"SuperBids{current_time}"

try:
    final_temp.to_excel(f"D:/Automation/OutputW/{folder_name}/{file}.xlsx")
    print('Done')
except Exception as e:
    print(f'Error: {e}')

browser.quit()

C:\ProgramData\Anaconda3\envs\samil\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\envs\samil\lib\site-packages\numpy\.libs\libopenblas.gk7gx5keq4f6uyo3p26ulgbqyhgqo7j4.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\envs\samil\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

260
Done

In [18]:
temp_data

,Client,Start Date,End Date,Count,Category,Zone,Cat_first,Cat_last,Split_Client_first,Split_Client_last,Location
0,Yes Bank,03-Aug-2024,03-Aug-2024,2,4W,East,4W,4W,77882 - Yes Bank,Assam Online Auction - 0608,Assam
1,Yes Bank,03-Aug-2024,03-Aug-2024,1,4W,East,4W,4W,77887 - Yes Bank,Jharkhand Online Auction - 0608,Jharkhand
2,Yes Bank,03-Aug-2024,03-Aug-2024,1,CE,East,CE,CE,77888 - Yes Bank,Orissa Online Auction - 0608,Orissa
3,Yes Bank,03-Aug-2024,03-Aug-2024,4,4W,East,4W,4W,77890 - Yes Bank,West Bengal Online Auction - 0608,West Bengal
4,Yes Bank,03-Aug-2024,03-Aug-2024,7,CV CE,East,CV CE,CV CE,77891 - Yes Bank,West Bengal Online Auction - 0608,West Bengal
...,...,...,...,...,...,...,...,...,...,...,...
185,Bajaj Finance,06-Aug-2024,06-Aug-2024,2,3W,East,3W,3W,78073 - Bajaj Finance,West Bengal Online Auction - 1008,West Bengal
186,Bajaj Finance,06-Aug-2024,06-Aug-2024,192,2W,East,2W,2W,78078 - Bajaj Finance,Orissa Online Auction - 1008,Orissa
187,Bajaj Finance,06-Aug-2024,06-Aug-2024,42,3W,East,3W,3W,78079 - Bajaj Finance,Orissa Online Auction - 1008,Orissa
188,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77774 - Consumer,Gujarat Online Auction - Aug,Gujarat
189,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77775 - Consumer,Maharashtra Online Auction - Aug,Maharashtra

In [21]:
new_temp=temp_data.copy()
new_temp

,Client,Start Date,End Date,Count,Category,Zone,Cat_first,Cat_last,Split_Client_first,Split_Client_last,Location
0,Yes Bank,03-Aug-2024,03-Aug-2024,2,4W,East,4W,4W,77882 - Yes Bank,Assam Online Auction - 0608,Assam
1,Yes Bank,03-Aug-2024,03-Aug-2024,1,4W,East,4W,4W,77887 - Yes Bank,Jharkhand Online Auction - 0608,Jharkhand
2,Yes Bank,03-Aug-2024,03-Aug-2024,1,CE,East,CE,CE,77888 - Yes Bank,Orissa Online Auction - 0608,Orissa
3,Yes Bank,03-Aug-2024,03-Aug-2024,4,4W,East,4W,4W,77890 - Yes Bank,West Bengal Online Auction - 0608,West Bengal
4,Yes Bank,03-Aug-2024,03-Aug-2024,7,CV CE,East,CV CE,CV CE,77891 - Yes Bank,West Bengal Online Auction - 0608,West Bengal
...,...,...,...,...,...,...,...,...,...,...,...
185,Bajaj Finance,06-Aug-2024,06-Aug-2024,2,3W,East,3W,3W,78073 - Bajaj Finance,West Bengal Online Auction - 1008,West Bengal
186,Bajaj Finance,06-Aug-2024,06-Aug-2024,192,2W,East,2W,2W,78078 - Bajaj Finance,Orissa Online Auction - 1008,Orissa
187,Bajaj Finance,06-Aug-2024,06-Aug-2024,42,3W,East,3W,3W,78079 - Bajaj Finance,Orissa Online Auction - 1008,Orissa
188,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77774 - Consumer,Gujarat Online Auction - Aug,Gujarat
189,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77775 - Consumer,Maharashtra Online Auction - Aug,Maharashtra

In [22]:
new_temp['1'] = new_temp.apply(lambda row: row['Client'].replace(row['Category'].replace(',', ''), ''), axis=1)
new_temp['2'] = new_temp.apply(lambda row: row['Client'].replace(row['Category'], ''), axis=1)
new_temp

,Client,Start Date,End Date,Count,Category,Zone,Cat_first,Cat_last,Split_Client_first,Split_Client_last,Location,1,2
0,Yes Bank,03-Aug-2024,03-Aug-2024,2,4W,East,4W,4W,77882 - Yes Bank,Assam Online Auction - 0608,Assam,Yes Bank,Yes Bank
1,Yes Bank,03-Aug-2024,03-Aug-2024,1,4W,East,4W,4W,77887 - Yes Bank,Jharkhand Online Auction - 0608,Jharkhand,Yes Bank,Yes Bank
2,Yes Bank,03-Aug-2024,03-Aug-2024,1,CE,East,CE,CE,77888 - Yes Bank,Orissa Online Auction - 0608,Orissa,Yes Bank,Yes Bank
3,Yes Bank,03-Aug-2024,03-Aug-2024,4,4W,East,4W,4W,77890 - Yes Bank,West Bengal Online Auction - 0608,West Bengal,Yes Bank,Yes Bank
4,Yes Bank,03-Aug-2024,03-Aug-2024,7,CV CE,East,CV CE,CV CE,77891 - Yes Bank,West Bengal Online Auction - 0608,West Bengal,Yes Bank,Yes Bank
...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Bajaj Finance,06-Aug-2024,06-Aug-2024,2,3W,East,3W,3W,78073 - Bajaj Finance,West Bengal Online Auction - 1008,West Bengal,Bajaj Finance,Bajaj Finance
186,Bajaj Finance,06-Aug-2024,06-Aug-2024,192,2W,East,2W,2W,78078 - Bajaj Finance,Orissa Online Auction - 1008,Orissa,Bajaj Finance,Bajaj Finance
187,Bajaj Finance,06-Aug-2024,06-Aug-2024,42,3W,East,3W,3W,78079 - Bajaj Finance,Orissa Online Auction - 1008,Orissa,Bajaj Finance,Bajaj Finance
188,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77774 - Consumer,Gujarat Online Auction - Aug,Gujarat,Consumer,Consumer
189,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77775 - Consumer,Maharashtra Online Auction - Aug,Maharashtra,Consumer,Consumer

In [33]:
new_temp['Cat_first']=new_temp['Category'].apply(lambda x:x.split(',')[0]).str.strip()
new_temp['Cat_last']=new_temp['Category'].apply(lambda x:x.split(',')[-1]).str.strip()
new_temp

,Client,Start Date,End Date,Count,Category,Zone,Cat_first,Cat_last,Split_Client_first,Split_Client_last,Location,1,2,Processed
0,Yes Bank,03-Aug-2024,03-Aug-2024,2,4W,East,4W,4W,77882 - Yes Bank,Assam Online Auction - 0608,Assam,Yes Bank,Yes Bank,
1,Yes Bank,03-Aug-2024,03-Aug-2024,1,4W,East,4W,4W,77887 - Yes Bank,Jharkhand Online Auction - 0608,Jharkhand,Yes Bank,Yes Bank,
2,Yes Bank,03-Aug-2024,03-Aug-2024,1,CE,East,CE,CE,77888 - Yes Bank,Orissa Online Auction - 0608,Orissa,Yes Bank,Yes Bank,
3,Yes Bank,03-Aug-2024,03-Aug-2024,4,4W,East,4W,4W,77890 - Yes Bank,West Bengal Online Auction - 0608,West Bengal,Yes Bank,Yes Bank,
4,Yes Bank,03-Aug-2024,03-Aug-2024,7,CV CE,East,CV CE,CV CE,77891 - Yes Bank,West Bengal Online Auction - 0608,West Bengal,Yes Bank,Yes Bank,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Bajaj Finance,06-Aug-2024,06-Aug-2024,2,3W,East,3W,3W,78073 - Bajaj Finance,West Bengal Online Auction - 1008,West Bengal,Bajaj Finance,Bajaj Finance,
186,Bajaj Finance,06-Aug-2024,06-Aug-2024,192,2W,East,2W,2W,78078 - Bajaj Finance,Orissa Online Auction - 1008,Orissa,Bajaj Finance,Bajaj Finance,
187,Bajaj Finance,06-Aug-2024,06-Aug-2024,42,3W,East,3W,3W,78079 - Bajaj Finance,Orissa Online Auction - 1008,Orissa,Bajaj Finance,Bajaj Finance,
188,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77774 - Consumer,Gujarat Online Auction - Aug,Gujarat,Consumer,Consumer,
189,Consumer,01-Aug-2024,01-Aug-2024,10,4W,West,4W,4W,77775 - Consumer,Maharashtra Online Auction - Aug,Maharashtra,Consumer,Consumer,

In [35]:
#new_t['Split_Client3'] = new_t.apply(lambda row: row['Client'].split(row['Cat_first'])[0].strip(), axis=1)
new_temp['Final_client'] = new_temp['Split_Client3'].apply(lambda x: x.split('-')[1].strip())
#new_t['Split_Client2'] = new_t.apply(lambda row: row['Client'].split(row['Cat_last'])[-1].strip(), axis=1)
new_temp['final_location'] = new_temp['Split_Client2'].apply(lambda x:x.split('Online')[0])
new_temp

KeyError: 'Split_Client3'